# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongoPractica
    ports:
      - 27017:27017
    expose:
      - 27017
    #volumes:

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    #restart: always


  mongo-express:
    image: mongo-express
    container_name: desktop_mongo_express_practica
    restart: always
    depends_on: 
    - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  #volumes:
   # mongo-vol:

  #networks:
    #mongo-network:
     # driver: bridge
